### ISSUE TITLE
The API settings page shows 404

### ISSUE THREAD

**Issue by mudrd8mz** [unicheck/moodle-plagiarism_unicheckcorp#5]
When i am not logged in to unicheck.com and I click on the link "Open unicheck.com admin account to view/copy Client ID/API Secret" in Moodle, I get an error 404 page on URL https://corpapi.unicheck.com/profile/apisettings

![image](https://user-images.githubusercontent.com/85831/33036115-cfa08da4-ce2d-11e7-9c8c-9576992b13f0.png)

![image](https://user-images.githubusercontent.com/85831/33036137-e101f1b4-ce2d-11e7-9fb8-29ae042efab3.png)

If you need to be logged in to unicheck.com to make it work, a redirect to the login page would help.

**Comment by mundiir** [comment]
Fixed in #7, #6
