### ISSUE TITLE
Update version number to use YYYYMMDDVV

### ISSUE THREAD

**Issue by sayoder** [unicheck/moodle-plagiarism_unicheckcorp#62]
Greetings,

The canonical version number for v2.4.3 is still 2018021533 - should this be changed to 2019093000 or similar?

Thanks.

**Comment by mundiir** [comment]
Hi @MortimerMcMire315 

Thanks for the suggestion.
At the moment, we have 2 stable branches:
- https://github.com/unicheck/moodle-plagiarism_unicheckcorp/tree/release/1.x for Moodle 2.7-3.2
- https://github.com/unicheck/moodle-plagiarism_unicheckcorp/tree/release/2.x for Moodle 3.3-3.8

We use Moodle recommendations for version control and only change XX within the stable version

> If multiple stable branches of the plugin are maintained, the date part YYYYMMDD should be frozen at the branch forking date and the XX is used for incrementing the value on the given stable branch (allowing up to 100 updates on the given stable branch)

See https://docs.moodle.org/dev/version.php for more details.

**Comment by sayoder** [comment]
Thanks for this explanation. I wasn't aware that this was Moodle's recommended protocol.
